# Personal Portfolio Configuration
# Built using modern-resume-theme

# Site settings
title: "Rakibul Hasan Rizvi"
description: "Linux & VoIP Specialist | Systems Engineer | Future DevOps Engineer"
url: "https://rakibulhasanrizvi.github.io"

# Personal info
name: "Rakibul Hasan Rizvi"
job_title: "Systems Engineer | Linux & VoIP Specialist"
email: "rakibulhasanrizvi@yahoo.com"
phone: "+8801679343895"
location: "Bangladesh"
github_username: "rakibulhasanrizvi"
linkedin_username: "rakibulhasanrizvi"
# You can add your real links later

# About Section
about_title: "About Me"
about_content: |
  I’m a Systems Engineer experienced in managing Linux-based environments, VoIP infrastructures (Issabel, Asterisk), and virtualized servers (Proxmox).  
  Passionate about automation, DevOps, and cloud computing.  
  Currently focused on building scalable and secure communication systems — and learning to become a professional DevOps Engineer.

# Experience Section
experience_title: "Experience"
experience:
  - company: "Agni Systems PLC"
    position: "Systems Engineer"
    duration: "August 2023 - Present"
    summary: |
      - Maintain and administer Linux servers for VoIP and mail infrastructure.  
      - Manage Issabel and Asterisk PBX with SIP trunks and call routing.  
      - Support IPTSP operations and ensure high availability.  
      - Deploy and monitor Proxmox virtual environments.  
      - Provide mail server support and security hardening.

# Skills Section
skills_title: "Skills"
skills:
  - name: "Linux Server Administration"
    level: Expert
  - name: "Asterisk / Issabel / VoIP"
    level: Expert
  - name: "Proxmox Virtualization"
    level: Expert
  - name: "Mail Server & Security"
    level: Advance
  - name: "Bash & Python Scripting"
    level: Advance
  - name: "Networking & Subnetting"
    level: Advance
  - name: "DevOps Tools (Docker, Ansible, Terraform)"
    level: Learning
  - name: "Cloud (AWS, GCP)"
    level: Beginner

# Education Section
education_title: "Education"
education:
  - degree: "Bachelor’s in Computer Science & Engineering"
    institution: "American International University-Bangladesh"
    period: "2018 - 2021"

# Projects Section
projects_title: "Highlighted Projects"
projects:
  - name: "Call Center Alias Dialing System"
    link: "https://github.com/rakibulhasanrizvi"
    description: "Database-driven Issabel call routing system where agents dial short aliases mapped to hidden real numbers."

  - name: "Secure Mail & VoIP Infrastructure"
    description: "Implemented secure Linux-based email and VoIP environments with firewall, anti-spam, and failover strategies."

# Footer
footer_show_references: false
