# Site Settings
repository: sproogen/modern-resume-theme
remote_theme: sproogen/modern-resume-theme
favicon: images/favicon.ico
darkmode: true

# Personal Info
name: "Rakibul Hasan Rizvi"
title: "System Engineer | Linux & VoIP Specialist | Future DevOps Engineer"
email: "your-email@example.com"
phone: "+8801XXXXXXXXX"
location: "Bangladesh"
website: "https://rakibulhasanrizvi.github.io"

# Social Links
github_username: rakibulhasanrizvi
linkedin_username: rakibulhasanrizvi

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I’m a Systems Engineer experienced in managing Linux-based environments, VoIP infrastructures (Issabel, Asterisk), and virtualized servers (Proxmox).  
  Passionate about automation, DevOps, and cloud computing.  
  Currently focused on building scalable and secure communication systems — and learning to become a professional DevOps Engineer.

# Content Sections
content:
  - title: "Experience"
    layout: list
    content:
      - layout: left
        title: "IT & Telecom Services Provider"
        sub_title: "Systems Engineer"
        caption: "Present"
        description: |
          - Maintain and administer Linux servers for VoIP and mail infrastructure.  
          - Manage Issabel and Asterisk PBX with SIP trunks and call routing.  
          - Support IPTSP operations and ensure high availability.  
          - Deploy and monitor Proxmox virtual environments.  
          - Provide mail server support and security hardening.

  - title: "Skills"
    layout: list
    content:
      - layout: top-middle
        description: |
          **Linux Server Administration**  
          **Asterisk / Issabel / VoIP Systems**  
          **Proxmox Virtualization**  
          **Mail Server & Security Management**  
          **Bash & Python Scripting**  
          **Networking & Subnetting**  
          **DevOps Tools:** Docker, Ansible, Terraform  
          **Cloud Platforms:** AWS, GCP (Beginner)

  - title: "Projects"
    layout: list
    content:
      - layout: left
        title: "Call Center Alias Dialing System"
        link: "https://github.com/rakibulhasanrizvi"
        description: |
          Designed a database-driven Issabel call routing system where agents dial short aliases mapped to hidden real numbers.

      - layout: left
        title: "Secure Mail & VoIP Infrastructure"
        description: |
          Implemented secure Linux-based email and VoIP environments with firewall, anti-spam, and failover strategies.

  - title: "Education"
    layout: list
    content:
      - layout: left
        title: "Bachelor’s in Computer Science & Engineering"
        sub_title: "Your University Name"
        caption: "—"
        description: ""

# Footer
footer_show_references: false
